# Generated by Django 2.2.5 on 2019-09-12 07:11

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0018_auto_20160802_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontranslation',
            name='affiliation',
            field=models.CharField(default='', help_text='Provide the affiliation of this person', max_length=255, verbose_name='affiliation'),
        ),
        migrations.AddField(
            model_name='persontranslation',
            name='report_description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', help_text="Provide the description of this person's report.", verbose_name='report description'),
        ),
        migrations.AddField(
            model_name='persontranslation',
            name='report_title',
            field=models.CharField(default='', help_text="Provide the title name of this person's report.", max_length=255, verbose_name='report title'),
        ),
        migrations.AlterField(
            model_name='grouptranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_people.Group'),
        ),
        migrations.AlterField(
            model_name='peopleplugin',
            name='show_links',
            field=models.BooleanField(default=True, verbose_name='Show links to Detail Page'),
        ),
        migrations.AlterField(
            model_name='persontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_people.Person'),
        ),
    ]
